const data = {
    products: [
        {
            name: 'Bộ áo bóng đá Flow',
            slug: 'bo-ao-bong-da-flow1',
            category: 'Trang phục thi đấu',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'Bộ quần áo bóng đá Flow thun lạnh cao cấp, thấm hút mồ hôi, vải mát, mềm mịn',
        },
        {
            name: 'Bộ áo bóng đá Flow',
            slug: 'bo-ao-bong-da-flow2',
            category: 'Trang phục thi đấu',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'Bộ quần áo bóng đá Flow thun lạnh cao cấp, thấm hút mồ hôi, vải mát, mềm mịn',
        },
        {
            name: 'Bộ áo bóng đá Flow',
            slug: 'bo-ao-bong-da-flow3',
            category: 'Trang phục thi đấu',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'Bộ quần áo bóng đá Flow thun lạnh cao cấp, thấm hút mồ hôi, vải mát, mềm mịn',
        },
        {
            name: 'Bộ áo bóng đá Flow',
            slug: 'bo-ao-bong-da-flow4',
            category: 'Trang phục thi đấu',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'Bộ quần áo bóng đá Flow thun lạnh cao cấp, thấm hút mồ hôi, vải mát, mềm mịn',
        },
    ],
};
export default data;